### ISSUE TITLE
Correct use-level of Exceptions

### ISSUE THREAD

**Issue by Ramizjon** [Ramizjon/LearnProjectParquet#6]
In class "UserRepository". Do not dismiss such kind of error and remove printStackTrace at all from here. Moreover Repository must throw up any excpeptions and only upstream logic should decide if this particular exception shall be dismissed.

**Comment by btrofimov** [comment]
Also please add try catch section where it is relevant (upstream code like App.main or Mapper.map)
https://github.com/Ramizjon/LearnProjectParquet/blob/master/src/main/java/com/segmentreader/mapreduce/AbstractUserSegmentsMapper.java#L26
Ad for Mapper.map please count failed events.
